runtime: nodejs
vm: true


handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html
  expiration: "15m"

- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)

  - url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)

skip_files:
  - ^(.*/)?.*/node_modules/.*$